package livinnx;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/* @author natymartinez04*/
public class Frame extends javax.swing.JFrame {

    BaseDeDatos db = new BaseDeDatos();
    Connection conectar;
    Usuario usuario;

    /**
     * Creates new form Inicio
     */
    public Frame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon("src/livinnx/resources/logolivinnx.png").getImage());
        String directory = "LivinnxBD.accdb";
        conectar = db.connection(directory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PInicio = new javax.swing.JPanel();
        labelcon = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelSubName = new javax.swing.JLabel();
        panelTop = new javax.swing.JPanel();
        buttonRegister = new javax.swing.JButton();
        buttonLogIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Livinnx Reservas");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1080, 720));
        setMinimumSize(new java.awt.Dimension(590, 550));
        setResizable(false);

        PInicio.setBackground(new java.awt.Color(255, 255, 255));
        PInicio.setLayout(null);

        labelcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livinnx/resources/logolivinnx.png"))); // NOI18N
        PInicio.add(labelcon);
        labelcon.setBounds(360, 110, 190, 312);

        labelName.setBackground(new java.awt.Color(255, 255, 255));
        labelName.setFont(new java.awt.Font("PT Serif Caption", 1, 60)); // NOI18N
        labelName.setForeground(new java.awt.Color(0, 0, 153));
        labelName.setText("Livinnx");
        PInicio.add(labelName);
        labelName.setBounds(20, 140, 290, 83);

        labelSubName.setBackground(new java.awt.Color(255, 255, 255));
        labelSubName.setFont(new java.awt.Font("PT Serif Caption", 1, 60)); // NOI18N
        labelSubName.setText("RESERVAS");
        PInicio.add(labelSubName);
        labelSubName.setBounds(20, 240, 350, 71);

        panelTop.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        PInicio.add(panelTop);
        panelTop.setBounds(0, 0, 600, 50);

        buttonRegister.setBackground(new java.awt.Color(255, 255, 255));
        buttonRegister.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livinnx/resources/button_registro.png"))); // NOI18N
        buttonRegister.setBorder(null);
        buttonRegister.setBorderPainted(false);
        buttonRegister.setContentAreaFilled(false);
        buttonRegister.setFocusPainted(false);
        buttonRegister.setMaximumSize(new java.awt.Dimension(270, 62));
        buttonRegister.setMinimumSize(new java.awt.Dimension(270, 62));
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });
        PInicio.add(buttonRegister);
        buttonRegister.setBounds(20, 350, 164, 60);

        buttonLogIn.setBackground(new java.awt.Color(255, 255, 255));
        buttonLogIn.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livinnx/resources/button_iniciar-sesion-2.png"))); // NOI18N
        buttonLogIn.setBorder(null);
        buttonLogIn.setBorderPainted(false);
        buttonLogIn.setContentAreaFilled(false);
        buttonLogIn.setFocusPainted(false);
        buttonLogIn.setMaximumSize(new java.awt.Dimension(270, 62));
        buttonLogIn.setMinimumSize(new java.awt.Dimension(270, 62));
        buttonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogInActionPerformed(evt);
            }
        });
        PInicio.add(buttonLogIn);
        buttonLogIn.setBounds(10, 420, 220, 60);

        getContentPane().add(PInicio, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * This method assigns and action to the Log in button once it's created
     * When the button it's clicked, the first panel gets removed from the frame
     * Then the LogIn panel gets added to the frame
     * A listener is added to buttons of the LogIn panel for the frame to be able to change panels again (go back/ log in)
     * When the login button of the LogIn panel is pressed, it searches for a match in the database, if found, the frame displays the Reservas panel
     * If no match was found in the datebase a JOptionPane shows an error message
     * Finally, if a match was found, a listener is also added to the logOut button on Reservas, to be able to return to the LogIn panel
    */

    private void buttonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogInActionPerformed
        LogIn log = new LogIn();
        this.remove(PInicio);
        this.add(log, BorderLayout.CENTER);
        revalidate();
        repaint();
        log.getBackButton().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                remove(log);
                add(PInicio, BorderLayout.CENTER);
                revalidate();
                repaint();
            }

        });
        log.getLogButton().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                String query_buscarusuario = "SELECT Usuario,Clave FROM Personas WHERE Usuario='" + log.getUser() + "' AND Clave='" + log.getUserPassword() + "'";
                String titles_table[] = {"Usuario", "Clave"};
                DefaultTableModel T6 = new DefaultTableModel(null, titles_table);
                String Results[] = new String[2];
                T6 = db.SEARCH(conectar, query_buscarusuario, Results, T6);
                int cont = T6.getRowCount();

                if (cont == 0) {
                    JOptionPane.showMessageDialog(null, "No hay una persona con ese Usuario o Clave registrado");
                } else {
                    String us = log.getUser();
                    usuario = new Usuario(us);
                    Reservas res = new Reservas(usuario);
                    remove(log);
                    add(res, BorderLayout.CENTER);
                    res.setgreetLabel();
                    setSize(760, 560);
                    res.getBackButton().addActionListener(new ActionListener(){
                        @Override
                        public void actionPerformed(ActionEvent ae) {
                            setSize(590, 550);
                            remove(res);
                            add(log, BorderLayout.CENTER);
                            log.getUserField().setText("Ingrese nombre de usuario");
                            log.getUserField().setForeground(Color.GRAY);
                            log.getPasswordField().setText("");
                            revalidate();
                            repaint();
                        }
                    });
                    revalidate();
                    repaint();
                }
            }

        });
    }//GEN-LAST:event_buttonLogInActionPerformed
    
    /**
     * This method assigns and action to the Register button once it's created
     * When the button is clicked, the first panel gets removed from the frame
     * Then the Registro panel gets added to the frame
     * A listener is added to the go back button of the Registro panel, to allow the frame to switch panels back
     */
    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        Registro r = new Registro();
        this.remove(PInicio);
        this.add(r, BorderLayout.CENTER);
        revalidate();
        repaint();
        r.getBackButton().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                remove(r);
                add(PInicio, BorderLayout.CENTER);
                revalidate();
                repaint();
            }
        });


    }//GEN-LAST:event_buttonRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PInicio;
    private javax.swing.JButton buttonLogIn;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSubName;
    private javax.swing.JLabel labelcon;
    private javax.swing.JPanel panelTop;
    // End of variables declaration//GEN-END:variables
}
