/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package livinnx;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aland
 */
public class LogIn extends javax.swing.JPanel {

    BaseDeDatos db = new BaseDeDatos();
    Connection conectar;
    Usuario usuario;
    
    public LogIn() {
        initComponents();
        String directory = "LivinnxBD.accdb"; 
        conectar= db.connection(directory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PInicio = new javax.swing.JPanel();
        labelcon = new javax.swing.JLabel();
        labelSubName = new javax.swing.JLabel();
        panelTop = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        buttonLogIn = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        PInicio.setBackground(new java.awt.Color(255, 255, 255));
        PInicio.setLayout(null);

        labelcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livinnx/resources/logolivinnx.png"))); // NOI18N
        PInicio.add(labelcon);
        labelcon.setBounds(380, 130, 200, 312);

        labelSubName.setBackground(new java.awt.Color(255, 255, 255));
        labelSubName.setFont(new java.awt.Font("PT Serif Caption", 1, 48)); // NOI18N
        labelSubName.setText("Iniciar Sesión");
        PInicio.add(labelSubName);
        labelSubName.setBounds(20, 70, 330, 71);

        panelTop.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        PInicio.add(panelTop);
        panelTop.setBounds(0, 0, 600, 50);

        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("PT Serif Caption", 1, 24)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 0, 153));
        passwordLabel.setText("Contraseña");
        PInicio.add(passwordLabel);
        passwordLabel.setBounds(20, 280, 140, 20);

        userLabel.setBackground(new java.awt.Color(255, 255, 255));
        userLabel.setFont(new java.awt.Font("PT Serif Caption", 1, 24)); // NOI18N
        userLabel.setForeground(new java.awt.Color(0, 0, 153));
        userLabel.setText("Usuario");
        PInicio.add(userLabel);
        userLabel.setBounds(20, 170, 100, 20);

        userTextField.setForeground(new java.awt.Color(204, 204, 204));
        userTextField.setText("Ingrese nombre de usuario");
        userTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTextFieldMouseClicked(evt);
            }
        });
        userTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextFieldActionPerformed(evt);
            }
        });
        PInicio.add(userTextField);
        userTextField.setBounds(20, 210, 230, 30);

        buttonLogIn.setBackground(new java.awt.Color(255, 255, 255));
        buttonLogIn.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livinnx/resources/button_iniciar-sesion (1).png"))); // NOI18N
        buttonLogIn.setBorderPainted(false);
        buttonLogIn.setContentAreaFilled(false);
        buttonLogIn.setFocusPainted(false);
        buttonLogIn.setMaximumSize(new java.awt.Dimension(270, 62));
        buttonLogIn.setMinimumSize(new java.awt.Dimension(270, 62));
        buttonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogInActionPerformed(evt);
            }
        });
        PInicio.add(buttonLogIn);
        buttonLogIn.setBounds(20, 380, 150, 50);

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livinnx/resources/button_regresar (2).png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setFocusPainted(false);
        backButton.setMaximumSize(new java.awt.Dimension(270, 62));
        backButton.setMinimumSize(new java.awt.Dimension(270, 62));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        PInicio.add(backButton);
        backButton.setBounds(200, 380, 110, 50);

        passwordField.setToolTipText("Ingrese su contraseña aqui ");
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        PInicio.add(passwordField);
        passwordField.setBounds(20, 320, 230, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextFieldActionPerformed

    private void buttonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogInActionPerformed

    }//GEN-LAST:event_buttonLogInActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void userTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextFieldMouseClicked
        if(userTextField.getText().equalsIgnoreCase("Ingrese nombre de usuario")){
            userTextField.setText("");
            userTextField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_userTextFieldMouseClicked

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PInicio;
    private javax.swing.JButton backButton;
    private javax.swing.JButton buttonLogIn;
    private javax.swing.JLabel labelSubName;
    private javax.swing.JLabel labelcon;
    private javax.swing.JPanel panelTop;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables

    public JButton getBackButton() {
        return backButton;
    }
     public JButton getLogButton(){
        return buttonLogIn;
    }
    public String getUser(){
     return userTextField.getText();
    }
    public String getUserPassword(){
        return new String( passwordField.getPassword());
    }
}
